name: ragalahari_downloader
description: "A simple image downloader app for Ragalahari"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+5

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2
  path_provider: ^2.1.1
  permission_handler: ^11.0.0
  html: ^0.15.0
  http: ^1.3.0
  cached_network_image: ^3.2.3
  photo_view: ^0.14.0
  url_launcher: ^6.1.7
  device_info_plus: ^9.0.2
  shimmer: ^3.0.0
  open_filex: ^4.3.2
  webview_flutter: ^4.4.2
  webview_flutter_android: ^3.3.0
  webview_flutter_wkwebview: ^3.3.0
  intl: ^0.17.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.4.1
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/data/Fetched_StarZone_Data.csv
    - assets/logo.png

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  android: true
  ios: true

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21 # Optional: Set minimum Android SDK
  remove_alpha_ios: true # Optional: Remove alpha channel for iOS